apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-fabric
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/micheam/homelab-k3s
    targetRevision: main
    path: apps/minecraft-fabric
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft-fabric
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true