apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-readonly
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-readonly-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: agent-readonly
type: kubernetes.io/service-account-token
