apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-fabric-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: minecraft-fabric-data-pv
