apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: limno-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: limno-postgres
  template:
    metadata:
      labels:
        app: limno-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:18-alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - configMapRef:
            name: limnosrv-config
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - limno
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - limno
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
