apiVersion: v1
kind: Service
metadata:
  name: limnosrv
  labels:
    app: limnosrv
spec:
  type: NodePort
  selector:
    app: limnosrv
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
